---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version
  - ansible-galaxy install --roles-path=./tests/roles rahul0705.apache

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Test for Syntax
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --syntax-check
  # Test for Failure
  - >
    ansible-playbook -i tests/inventory tests/test.yml --become
    --connection=local --skip-tags generate_certs
  # Test for Idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml --become
    --connection=local --skip-tags generate_certs
    | grep -q 'changed=0.*failed=0'
  # Test for Success
  - >
    sudo crontab -l | grep "certbot renew"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
