---
# tasks file for ansible-certbot

- name: Install dependencies
  package:
    name: software-properties-common
    state: present
  tags:
    - install

- include_tasks: configure_{{ ansible_pkg_mgr }}.yml
  when:
    - ansible_pkg_mgr == "apt"
  tags:
    - install

- name: Install Certbot
  package:
    name: python-certbot-apache
    state: present
  tags:
    - install

- name: Generate certificates
  command: certbot --apache certonly --noninteractive --agree-tos --email {{ certbot_cert_email }} --domains {{ certbot_cert_domain }}
  args:
    creates: "{{ certbot_cert_directory }}"
  tags:
    - generate_certs

- name: Create automatic renewal cron job for cert
  cron:
    name: daily automatic renewal for {{ certbot_cert_domain }}
    special_time: daily
    job: certbot renew
    state: present
  tags:
    renew_certs
